server {
    listen 80;
    server_name localhost;

    root /var/www/html;
    index index.php index.html;

    set $cache_uri $uri;

    client_max_body_size 50M;
    large_client_header_buffers 4 32k;

    set $c_uri $query_string; # e.g. "param1=true&param4=false"
    set $cache_status 'HIT';


    if ($c_uri ~ (.*)(?:&|^)utm_source=[^&]*(.*)) {
        set $c_uri $1$2;
    }

    if ($c_uri ~ (.*)(?:&|^)utm_term=[^&]*(.*)) {
        set $c_uri $1$2;
    }

    if ($c_uri ~ (.*)(?:&|^)utm_campaign=[^&]*(.*)) {
        set $c_uri $1$2;
    }

    if ($c_uri ~ (.*)(?:&|^)utm_medium=[^&]*(.*)) {
        set $c_uri $1$2;
    }

    if ($c_uri ~ (.*)(?:&|^)utm_content=[^&]*(.*)) {
        set $c_uri $1$2;
    }

    # POST requests and urls with a query string should always go to PHP
    if ($request_method = POST) {
      set $cache_uri 'null cache';
      set $cache_status 'MISS';
    }

    if ($c_uri != "") {
      set $cache_uri 'null cache';
      set $cache_status 'MISS';
    }

    # Don't cache uris containing the following segments
    if ($request_uri ~* "(/wp-admin/|/xmlrpc.php|/wp-(app|cron|login|register|mail).php|wp-.*.php|/feed/|index.php|wp-comments-popup.php|wp-links-opml.php|wp-locations.php|sitemap(_index)?.xml|[a-z0-9_-]+-sitemap([0-9]+)?.xml)") {
      set $cache_uri 'null cache';
      set $cache_status 'MISS';
    }

    # Don't use the cache for logged in users or recent commenters
    if ($http_cookie ~* "comment_author|wordpress_[a-f0-9]+|wp-postpass|wordpress_logged_in") {
      set $cache_uri 'null cache';
      set $cache_status 'MISS';
    }


    location / {
      add_header X-Content-Type-Options nosniff;
      add_header X-XSS-Protection "1; mode=block";
      add_header Strict-Transport-Security "max-age=31536000; " always;
      add_header WP-Cache-Status $cache_status;
      try_files /wp-content/cache/supercache/$http_host/$cache_uri/index-https.html /wp-content/cache/supercache/$http_host/$cache_uri/index.html $uri $uri/ /index.php?$args;
    }

    location ~ ([^/]*)sitemap(.*).x(m|s)l$ {
      ## this redirects sitemap.xml to /sitemap_index.xml
      rewrite ^/sitemap.xml$ /sitemap_index.xml permanent;
      ## this makes the XML sitemaps work
      rewrite ^/([a-z]+)?-?sitemap.xsl$ /index.php?xsl=$1 last;
      rewrite ^/sitemap_index.xml$ /index.php?sitemap=1 last;
      rewrite ^/([^/]+?)-sitemap([0-9]+)?.xml$ /index.php?sitemap=$1&sitemap_n=$2 last;
      # START Nginx Rewrites for Rank Math Sitemaps
      rewrite ^/sitemap_index.xml$ /index.php?sitemap=1 last;
      rewrite ^/([^/]+?)-sitemap([0-9]+)?.xml$ /index.php?sitemap=$1&sitemap_n=$2 last;
      # END Nginx Rewrites for Rank Math Sitemaps
    }

    location ~ \.php$ {
      proxy_set_header        Host $host:$server_port;
      proxy_set_header        X-Real-IP $remote_addr;
      proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header        X-Forwarded-Proto $scheme;
      include snippets/fastcgi-php.conf;
      fastcgi_read_timeout 120;

      fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
      fastcgi_param DOCUMENT_ROOT $realpath_root;
      fastcgi_pass 127.0.0.1:9000;
      proxy_busy_buffers_size   512k;
      proxy_buffers   4 512k;
      proxy_buffer_size   256k;
      fastcgi_buffers 16 32k;
      fastcgi_buffer_size 32k;
      add_header X-Content-Type-Options nosniff;
      add_header X-XSS-Protection "1; mode=block";
      add_header Strict-Transport-Security "max-age=31536000; " always;
    }

    location ~ /\.ht {
      deny all;
    }
    location ~ /\.git {
      deny all;
    }
    location ~ /\.github {
      deny all;
    }
    location ~ /\.devcontainer {
      deny all;
    }
    location ~ /\.codeception {
      deny all;
    }
    location ~ /\.docker {
      deny all;
    }
    location ~ /\.ansible {
      deny all;
    }

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;
}